[2025-01-02T16:16:08.903+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-02T16:16:08.999+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-27T15:00:00+00:00 [queued]>
[2025-01-02T16:16:09.092+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-27T15:00:00+00:00 [queued]>
[2025-01-02T16:16:09.094+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 3
[2025-01-02T16:16:09.190+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_produce_data> on 2024-12-27 15:00:00+00:00
[2025-01-02T16:16:09.205+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=133) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-02T16:16:10.189+0000] {standard_task_runner.py:72} INFO - Started process 163 to run task
[2025-01-02T16:16:10.195+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'api_to_kafka_pipeline', 'fetch_and_produce_data', 'scheduled__2024-12-27T15:00:00+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/api_to_kafka_dag.py', '--cfg-path', '/tmp/tmpvoy6uu39']
[2025-01-02T16:16:11.990+0000] {standard_task_runner.py:105} INFO - Job 188: Subtask fetch_and_produce_data
[2025-01-02T16:16:12.390+0000] {task_command.py:467} INFO - Running <TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-27T15:00:00+00:00 [running]> on host 90575834d22b
[2025-01-02T16:16:12.897+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_to_kafka_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_produce_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-27T15:00:00+00:00'
[2025-01-02T16:16:12.898+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-02T16:16:13.003+0000] {api_to_kafka_dag.py:85} INFO - Fetching data for IBM at 5min interval
[2025-01-02T16:16:13.279+0000] {api_to_kafka_dag.py:93} INFO - Processing and sending data to Kafka
[2025-01-02T16:30:14.932+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-01-02T16:30:14.934+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-02T16:30:14.936+0000] {process_utils.py:132} INFO - Sending 15 to group 163. PIDs of all processes in the group: [163]
[2025-01-02T16:30:14.937+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 163
[2025-01-02T16:31:20.429+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=163, name='airflow task ru', status='sleeping', started='16:16:09') did not respond to SIGTERM. Trying SIGKILL
[2025-01-02T16:31:20.432+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 163
[2025-01-02T16:31:20.446+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=163, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='16:16:09') (163) terminated with exit code -9
[2025-01-02T16:31:20.448+0000] {standard_task_runner.py:190} ERROR - ('Job 188 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
