[2024-12-30T15:20:18.479+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T15:20:18.585+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-27T14:00:00+00:00 [queued]>
[2024-12-30T15:20:18.666+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-27T14:00:00+00:00 [queued]>
[2024-12-30T15:20:18.668+0000] {taskinstance.py:2866} INFO - Starting attempt 6 of 3
[2024-12-30T15:20:18.867+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_produce_data> on 2024-12-27 14:00:00+00:00
[2024-12-30T15:20:18.966+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=141) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-30T15:20:18.968+0000] {standard_task_runner.py:72} INFO - Started process 163 to run task
[2024-12-30T15:20:18.972+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'api_to_kafka_pipeline', 'fetch_and_produce_data', 'scheduled__2024-12-27T14:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/api_to_kafka_dag.py', '--cfg-path', '/tmp/tmpit_gsw6y']
[2024-12-30T15:20:19.064+0000] {standard_task_runner.py:105} INFO - Job 147: Subtask fetch_and_produce_data
[2024-12-30T15:20:19.469+0000] {task_command.py:467} INFO - Running <TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-27T14:00:00+00:00 [running]> on host 6dfcffa93945
[2024-12-30T15:20:20.262+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_to_kafka_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_produce_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-27T14:00:00+00:00'
[2024-12-30T15:20:20.264+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T15:20:20.461+0000] {api_to_kafka_dag.py:85} INFO - Fetching data for IBM at 5min interval
[2024-12-30T15:20:21.801+0000] {api_to_kafka_dag.py:93} INFO - Processing and sending data to Kafka
[2024-12-30T20:33:20.843+0000] {job.py:229} INFO - Heartbeat recovered after 4570.31 seconds
[2024-12-30T20:33:31.504+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-30T20:33:31.506+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-30T20:33:31.521+0000] {process_utils.py:132} INFO - Sending 15 to group 163. PIDs of all processes in the group: [163]
[2024-12-30T20:33:31.527+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 163
[2024-12-30T20:34:31.557+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=163, name='airflow task ru', status='sleeping', started='15:20:17') did not respond to SIGTERM. Trying SIGKILL
[2024-12-30T20:34:31.571+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 163
[2024-12-30T20:34:31.624+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=163, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='15:20:17') (163) terminated with exit code -9
[2024-12-30T20:34:31.657+0000] {standard_task_runner.py:190} ERROR - ('Job 147 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
