[2024-12-26T17:04:26.854+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T17:04:26.922+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data manual__2024-12-26T06:18:16.682582+00:00 [queued]>
[2024-12-26T17:04:26.930+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data manual__2024-12-26T06:18:16.682582+00:00 [queued]>
[2024-12-26T17:04:26.931+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-26T17:04:27.023+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_produce_data> on 2024-12-26 06:18:16.682582+00:00
[2024-12-26T17:04:27.119+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=285) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-26T17:04:27.210+0000] {standard_task_runner.py:72} INFO - Started process 309 to run task
[2024-12-26T17:04:27.211+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'api_to_kafka_pipeline', 'fetch_and_produce_data', 'manual__2024-12-26T06:18:16.682582+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/api_to_kafka_dag.py', '--cfg-path', '/tmp/tmpresb09mi']
[2024-12-26T17:04:27.310+0000] {standard_task_runner.py:105} INFO - Job 98: Subtask fetch_and_produce_data
[2024-12-26T17:04:27.618+0000] {task_command.py:467} INFO - Running <TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data manual__2024-12-26T06:18:16.682582+00:00 [running]> on host bd7ba946b34c
[2024-12-26T17:04:28.325+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_to_kafka_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_produce_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T06:18:16.682582+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T06:18:16.682582+00:00'
[2024-12-26T17:04:28.411+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T17:04:28.431+0000] {api_to_kafka_dag.py:85} INFO - Fetching data for IBM at 5min interval
[2024-12-26T17:04:28.685+0000] {api_to_kafka_dag.py:95} INFO - Processing and sending data to Kafka
[2024-12-26T18:27:04.063+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-26T18:27:04.069+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-26T18:27:04.072+0000] {process_utils.py:132} INFO - Sending 15 to group 309. PIDs of all processes in the group: [309]
[2024-12-26T18:27:04.073+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 309
[2024-12-26T18:28:04.087+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=309, name='airflow task ru', status='sleeping', started='17:04:26') did not respond to SIGTERM. Trying SIGKILL
[2024-12-26T18:28:04.093+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 309
[2024-12-26T18:28:04.101+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=309, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='17:04:26') (309) terminated with exit code -9
[2024-12-26T18:28:04.102+0000] {standard_task_runner.py:190} ERROR - ('Job 98 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
