[2024-12-26T18:34:32.360+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T18:34:32.375+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-26T17:00:00+00:00 [queued]>
[2024-12-26T18:34:32.382+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-26T17:00:00+00:00 [queued]>
[2024-12-26T18:34:32.383+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-12-26T18:34:32.397+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_produce_data> on 2024-12-26 17:00:00+00:00
[2024-12-26T18:34:32.402+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'api_to_kafka_pipeline', 'fetch_and_produce_data', 'scheduled__2024-12-26T17:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/api_to_kafka_dag.py', '--cfg-path', '/tmp/tmp0l0q7py2']
[2024-12-26T18:34:32.403+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4958) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-26T18:34:32.404+0000] {standard_task_runner.py:105} INFO - Job 101: Subtask fetch_and_produce_data
[2024-12-26T18:34:32.405+0000] {standard_task_runner.py:72} INFO - Started process 4962 to run task
[2024-12-26T18:34:32.449+0000] {task_command.py:467} INFO - Running <TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-26T17:00:00+00:00 [running]> on host bd7ba946b34c
[2024-12-26T18:34:32.523+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_to_kafka_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_produce_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-26T17:00:00+00:00'
[2024-12-26T18:34:32.525+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T18:34:32.535+0000] {api_to_kafka_dag.py:85} INFO - Fetching data for IBM at 5min interval
[2024-12-26T18:34:32.720+0000] {api_to_kafka_dag.py:95} INFO - Processing and sending data to Kafka
[2024-12-26T21:41:04.572+0000] {job.py:229} INFO - Heartbeat recovered after 5453.68 seconds
[2024-12-26T21:41:16.009+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2024-12-26T21:41:16.014+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-26T21:41:16.028+0000] {process_utils.py:132} INFO - Sending 15 to group 4962. PIDs of all processes in the group: [4962]
[2024-12-26T21:41:16.038+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 4962
[2024-12-26T21:42:16.021+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=4962, name='airflow task ru', status='sleeping', started='18:34:32') did not respond to SIGTERM. Trying SIGKILL
[2024-12-26T21:42:16.108+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 4962
[2024-12-26T21:42:16.202+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=4962, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='18:34:32') (4962) terminated with exit code -9
[2024-12-26T21:42:16.208+0000] {standard_task_runner.py:190} ERROR - ('Job 101 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
